name: Graphs CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory: [./graphs/omen-thumbnailmapping]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/foundry_prepare
      - uses: ./.github/actions/graph_prepare
        with:
          working_directory: ${{ matrix.working-directory }}
      - name: Run graph tests for ${{ matrix.working-directory }}
        run: graph test -l -f
        working-directory: ${{ matrix.working-directory }}
